import streamlit as st
import os
import base64
from pathlib import Path

# --- Configuration ---
# Defines where the plots are saved and which artists are being analyzed.
OUTPUT_DIR = 'output_plots' # Folder where the analysis script saves its output HTML files
ARTISTS_TO_ANALYZE = ['Eminem', 'Taylor Swift'] # List of artists whose data is being shown

# --- Streamlit Page Setup ---
# Sets up the main look and feel of the web application, including the title and introduction.
st.set_page_config(layout="wide", page_title="AI Music Intelligence Dashboard") # Configure page layout and title
st.title("AI for Music Intelligence: Lyrical Evolution and Thematic Profiling") # Main title of the dashboard
st.markdown("""
This dashboard presents the results of an AI-driven analysis of lyrical content from various artists.
It explores sentiment evolution, topic dominance, and key entities mentioned in their discographies.
""") # A brief description of the project
st.header("How to Use:") # Section header for instructions
st.markdown("""
1.  **Run the analysis script first:** Make sure you have run your main Python script (e.g., `music_intelligence_analysis.py`)
    that generates the `output_plots` directory and all the **interactive HTML** files.
2.  **Navigate the sections:** Use the sidebar or scroll down to view different aspects of the analysis.
3.  **Interactive Charts:** All charts displayed here are interactive. You can zoom, pan, and hover over data points for detailed information (tooltips).
""") # Instructions for using the dashboard

# --- Helper Function to Display HTML ---
# This function loads and displays the interactive HTML plot files generated by the analysis script.
def display_html_file(file_path, title):
    if os.path.exists(file_path): # Check if the HTML file exists
        st.subheader(title) # Display a subheader for the chart
        with open(file_path, 'r', encoding='utf-8') as f:
            html_content = f.read() # Read the content of the HTML file
        st.components.v1.html(html_content, height=600, scrolling=True) # Embed the HTML content into the Streamlit app
    else:
        st.warning(f"Interactive chart not found: `{file_path}`. Please run the analysis script first to generate it.") # Show a warning if file is missing

# --- Sidebar Navigation ---
# Creates the menu on the left side of the page, allowing users to choose what to view.
st.sidebar.title("Navigation") # Title for the sidebar
page_selection = st.sidebar.radio("Go to", ["Sentiment Analysis", "Topic Modeling", "Named Entity Recognition"]) # Radio buttons for navigation

# --- Sentiment Analysis Section ---
# Displays the interactive plot showing how lyrical sentiment changes over time.
if page_selection == "Sentiment Analysis":
    st.header("Lyrical Sentiment Evolution") # Section header
    st.markdown("This section visualizes the average lyrical sentiment over the years for selected artists.") # Description
    st.markdown("---") # A horizontal line for separation
    st.markdown("### Interactive Plot (Plotly) with Tooltips") # Sub-description for the plot
    display_html_file(os.path.join(OUTPUT_DIR, 'sentiment_evolution_interactive.html'),
                      'Interactive: Lyrical Sentiment Evolution Over Time with Next Year Prediction') # Call helper to display the plot

# --- Topic Modeling Section ---
# Shows interactive charts about the main themes (topics) in each artist's lyrics.
elif page_selection == "Topic Modeling":
    st.header("Lyrical Topic Dominance") # Section header
    st.markdown("These charts show how the dominant lyrical themes (topics) for each artist have shifted over their discography.") # Description
    for artist in ARTISTS_TO_ANALYZE: # Loop through each artist to display their topic charts
        st.markdown(f"---")
        st.markdown(f"### {artist}: Interactive Plot (Plotly) with Tooltips")
        display_html_file(os.path.join(OUTPUT_DIR, f'{artist}_topic_dominance_interactive.html'),
                          f'Interactive: {artist}: Lyrical Topic Dominance Over Time')

# --- Named Entity Recognition Section ---
# Presents interactive charts highlighting the most common names, places, and organizations mentioned in lyrics.
elif page_selection == "Named Entity Recognition":
    st.header("Key Lyrical Entities") # Section header
    st.markdown("This section highlights the most frequently mentioned entities (people, organizations, locations) in each artist's lyrics.") # Description
    for artist in ARTISTS_TO_ANALYZE: # Loop through each artist to display their entity charts
        st.markdown(f"---")
        st.markdown(f"### {artist}: Interactive Plot (Plotly) with Tooltips")
        display_html_file(os.path.join(OUTPUT_DIR, f'{artist}_overall_top_entities_interactive.html'),
                          f'Interactive: {artist}: Overall Top 10 Lyrical Entities')

